services:
  cone-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nginx-network
    environment:
      - FLASK_ENV=development
      - GEOSERVER_URL=http://conescout.duckdns.org/geoserver
    volumes:
      - ./templates:/usr/src/app/templates
      - ./static:/usr/src/app/static
      - ./app.py:/usr/src/app/app.py
      - ./routes.py:/usr/src/app/routes.py
      - ./routes_auth.py:/usr/src/app/routes_auth.py
      - ./auth.py:/usr/src/app/auth.py
      - ./utils:/usr/src/app/utils
      - ./api:/usr/src/app/api
    depends_on:
      - postgis
    restart: always
    ports:
      - "8000:8000"
    mem_limit: 256M
    mem_reservation: 128M

  nginx-container:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: custom-nginx
    ports:
      - "80:80"
    depends_on:
      - cone-app
      - geoserver
    networks:
      - nginx-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro
    restart: always
    mem_limit: 128M
    mem_reservation: 64M
    
  # certbot service removed for HTTP-only configuration
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;'"
  #   depends_on:
  #     - nginx-container

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.2
    environment:
      # Database Configuration
      - POSTGRES_DB=geoserver_db
      - POSTGRES_USER=geoserver
      - POSTGRES_PASSWORD=23vmoWpostgis
      - PGHOST=postgis
      - PGPORT=5432
      
      # Core Settings
      - INSTALL_EXTENSIONS=true
      - SKIP_DEMO_DATA=true
      
      # GeoWebCache Configuration
      - GEOWEBCACHE_CACHE_DIR=/opt/geoserver_data/gwc
      - GEOWEBCACHE_CONFIG_DIR=/opt/geoserver_data/gwc
      - GEOWEBCACHE_CACHE_MEMORY=256M
      - GEOWEBCACHE_METASTORE_JDBC_HOST=postgis
      - GEOWEBCACHE_METASTORE_JDBC_PORT=5432
      - GEOWEBCACHE_METASTORE_JDBC_DATABASE=geoserver_db
      - GEOWEBCACHE_METASTORE_JDBC_USER=geoserver
      - GEOWEBCACHE_METASTORE_JDBC_PASSWORD=23vmoWpostgis
      
      # Performance Tuning
      - JAVA_OPTS=-Xms256M -Xmx512M -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication
      - CATALINA_OPTS=-Xms256M -Xmx512M
      - GEOSERVER_OPTS=-DGEOSERVER_CSRF_DISABLED=true -Dorg.geotools.referencing.forceXY=true -Dorg.geotools.coverage.jaiext.enabled=true -DMAX_FEATURES=2000
      
      # Extensions
      - STABLE_EXTENSIONS=ysld,h2,importer,vectortiles,monitor,css,rat,wps
      - COMMUNITY_EXTENSIONS=
      
      # Other Settings
      - ENABLE_JSONP=true
      - MAX_FILTER_RULES=20
      - OPTIMIZE_LINE_WIDTH=false

    volumes:
      - geoserver-extensions:/opt/additional_libs
      - P:/Projects/szeb_geoserver_data:/opt/geoserver_data
      
    networks:
      - nginx-network
    depends_on:
      - postgis
    ports:
      - "8080:8080"
    restart: always
    mem_limit: 768M
    mem_reservation: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  postgis:
    build:
      context: ./postgis
      dockerfile: Dockerfile
    container_name: postgis_container
    environment:
      - POSTGRES_DB=geoserver_db
      - POSTGRES_USER=geoserver
      - POSTGRES_PASSWORD=23vmoWpostgis
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=512MB
      - POSTGRES_WORK_MEM=16MB
      - POSTGRES_MAINTENANCE_WORK_MEM=64MB
      - POSTGRES_RANDOM_PAGE_COST=2.0
      - POSTGRES_EFFECTIVE_IO_CONCURRENCY=50
      - GDAL_DATA=/usr/share/gdal
      - PROJ_LIB=/usr/share/proj
      - LD_LIBRARY_PATH=/usr/lib:/usr/lib/postgresql:/usr/lib/x86_64-linux-gnu:/usr/local/lib
    volumes:
      - I:/postgis_storage:/var/lib/postgresql/data
      - P:/Projects/szeb_geoserver_data:/opt/geoserver_data
    shm_size: '256mb'
    networks:
      - nginx-network
    ports:
      - "5432:5432"
    cpus: '2'
    mem_limit: 768M
    mem_reservation: 512M
    restart: always

networks:
  nginx-network:
    driver: bridge

volumes:
  geoserver-extensions:
    external: true
  postgis-data:
    driver: local