version: '3'

services:
  simple-login:
    build:
      context: .
      dockerfile: Dockerfile-simple-login
    ports:
      - "8001:8001"
    networks:
      - nginx-network
    restart: always
    volumes:
      - ./simple_login.py:/app/simple_login.py

networks:
  nginx-network:
    external: true
