services:
  nginx-container:
    depends_on:
      - cone-app
      - geoserver
      - postgis
    restart: unless-stopped
    
  geoserver:
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/geoserver/web/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
