global:
  scrape_interval: 10s  # Scrape metrics every 10 seconds

scrape_configs:
  - job_name: 'flask_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['cone-app:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

rule_files:
  - "alerts.yml"
