version: '3.8'

services:
  evac-app:
    image: evac-app
    volumes:
      - P:/nginx_evac_app:/usr/src/app
    networks:
      - nginx-network
    restart: always

  nginx-container:
    image: custom-nginx
    ports:
      - "80:80"
    depends_on:
      - evac-app
      - geoserver
    networks:
      - nginx-network
    restart: always

  geoserver:
    image: jwha/geoserver-modified-cors-2.25.x:latest
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ysld,h2,importer,vectortiles,monitor,css
      - COMMUNITY_EXTENSIONS=features-templating,ogcapi-features,ogcapi-images,ogcapi-maps,ogcapi-styles,ogcapi-tiles,mbtiles,mbtiles-store,wps
    volumes:
      - geoserver-extensions:/opt/additional_libs
      - P:/geoserver_data:/opt/geoserver_data
    networks:
      - nginx-network
    ports:
      - "8080:8080"  # Map port 8080 on the host to port 8080 in the container
    restart: always

networks:
  nginx-network:
    driver: bridge

volumes:
  geoserver-extensions:
    external: true
